# Generated by Django 5.2.8 on 2026-01-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_internship_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
