# Generated by Django 5.2.8 on 2026-01-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_arman'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('running', 'Running'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='internship',
            name='certificate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='internship',
            name='mentorship',
            field=models.CharField(max_length=50),
        ),
    ]
